import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import {GetStaticProps} from 'next';
import {Episode as EpisodeT, allEpisodes} from 'contentlayer/generated';
import Episode from '@/components/Episode';
import Page from '@/components/Page';
import Map from '@/components/Map';

type Props = {
  episodes: EpisodeT[];
};

export default function Home(props: Props) {
  return (
    <Page aside={<Map episodes={props.episodes} />}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <aside className={styles.map}></aside>
        <main>
          {props.episodes.map((e) => (
            <Episode episode={e} key={e._id} />
          ))}
        </main>
      </div>
    </Page>
  );
}

export const getStaticProps: GetStaticProps<Props> = async (context) => ({
  props: {
    episodes: allEpisodes,
  },
});
