name: Deploy

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: yarn
      - name: build RSS feed
        run:
          - yarn contentlayer build
          - yarn rss
          - rm -rf scripts .contentlayer
      - name: deploy
        run: yarn vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
